### ISSUE TITLE
can't load models @ predictions.py and Evals.py due keras 

### ISSUE THREAD

**Issue by Mahmoussam** [Mahmoud-Alazhary/GridGuard-Masters#1]
Traceback (most recent call last):
  File "...\Eval.py", line 23, in <module>
    __model1 = keras.saving.load_model(os.getcwd() + '\\Models\\model1.keras')
**AttributeError: module 'keras.saving' has no attribute 'load_model'**

Keras version: 2.11.0
python version: 3.7.8
pip version :20.2.4

**Comment by Mahmoussam** [comment]
according to [docs](https://keras.io/api/models/model_saving_apis/model_saving_and_loading/) ,it seems correct,isn't it?

**Comment by Abdullrahmen** [comment]
Good morning @Mahmoussam 
I forked the repo and tried to run the file and it worked for me (for Eval.py and predictions.py and keras version = 3.2.1) 
**so, please update your keras version to 3.2.1**
and let's standardize the version of each library and module to make sure this won't happen again

**Comment by Mahmoussam** [comment]
```>pip install keras==3.2.1
ERROR: Could not find a version that satisfies the requirement keras==3.2.1 (from versions: 0.2.0, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.2.1, 1.2.2, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0rc0, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0rc3, 2.6.0, 2.7.0rc0, 2.7.0rc2, 2.7.0, 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.10.0rc0, 2.10.0rc1, 2.10.0, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0rc3, 2.11.0)
ERROR: No matching distribution found for keras==3.2.1
```

-------

Strange, gonna look into this

**Comment by Mahmoussam** [comment]
After more investigation and updating my pip.
> ERROR: Ignored the following versions that require a different python version: 2.12.0 Requires-Python >=3.8;

----
 I am using py 3.7 that's why..

**Comment by Mahmoussam** [comment]
Still can't find keras 3.2.1 for some reason.
Edit:
Now it says i need py>=3.9 xD
let's see..
